### ISSUE TITLE
Path to Phase 0

### ISSUE THREAD

**Issue by exp7l** [exp7l/resilience#5]
Goal: usable testnet version

ETA: 7/24

Roles:
1. fund manager
2. staker
3. trader/holder
4. synth operator

Scope:
1. create a fund
2. rebalance positions for the fund, and get paid from the fees
3. create a synth as synth operator, and get paid from the fees
4. trade synths
5. stake collateral into vaults and funds

Out of scope:
1. hedging against debt
2. audit and deep dives into mainnet issues

Todos:
1. Double check debt tracking logic
2. Align on integration - names of functions, names of tokens, parameter etc
3. liquidation 
4. Uni tests
5. Integration tests
6. Triple check debt tracking logic : )
7. The absolute minimum of a UI features in scope, to show potential users
8. Testnet deployment!

**Comment by 0xkomada** [comment]
Sounds good!
